version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lobbyRoblox
      MYSQL_USER: adminjuegos
      MYSQL_PASSWORD: 123
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql-data: